====
Starting job 4773019 at Tue 18 Jan 17:44:57 GMT 2022 for user dc-wils7.
Running on nodes: m5298
====
RESET SET TO BE 0

Environment:

Code: /cosma/home/durham/dc-wils7/DESI/
Gold output dir.: /cosma5/data/durham/dc-wils7/GAMA4/
Randoms output dir: /cosma5/data/durham/dc-wils7/GAMA4/randoms/
Running gold pipeline; logging to logs/gama_gold.log
Running gen_kEcat.py; logging to logs/gama_kE.log
Running gen_zmax_cat.py; logging to logs/gama_zama.log
/cosma/home/durham/dc-wils7/DESI/cosmo.py:14: RuntimeWarning: invalid value encountered in log10
  return 5. * np.log10(cosmo.luminosity_distance(zs).value) + 25.
/cosma/home/durham/dc-wils7/.local/lib/python3.9/site-packages/astropy/cosmology/flrw.py:1072: IntegrationWarning: The occurrence of roundoff error is detected, which prevents 
  the requested tolerance from being achieved.  The error may be 
  underestimated.
  return quad(self._inv_efunc_scalar, z1, z2, args=self._inv_efunc_scalar_args)[0]
/cosma/home/durham/dc-wils7/.conda/envs/lumfn/lib/python3.9/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_comoving_distance_z1z2_scalar (vectorized)
  outputs = ufunc(*inputs)
/cosma/home/durham/dc-wils7/.local/lib/python3.9/site-packages/astropy/cosmology/flrw.py:1072: IntegrationWarning: The integral is probably divergent, or slowly convergent.
  return quad(self._inv_efunc_scalar, z1, z2, args=self._inv_efunc_scalar_args)[0]
/cosma/home/durham/dc-wils7/DESI/cosmo.py:14: RuntimeWarning: invalid value encountered in log10
  return 5. * np.log10(cosmo.luminosity_distance(zs).value) + 25.
/cosma/home/durham/dc-wils7/.local/lib/python3.9/site-packages/astropy/cosmology/flrw.py:1072: IntegrationWarning: The occurrence of roundoff error is detected, which prevents 
  the requested tolerance from being achieved.  The error may be 
  underestimated.
  return quad(self._inv_efunc_scalar, z1, z2, args=self._inv_efunc_scalar_args)[0]
/cosma/home/durham/dc-wils7/.conda/envs/lumfn/lib/python3.9/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_comoving_distance_z1z2_scalar (vectorized)
  outputs = ufunc(*inputs)
/cosma/home/durham/dc-wils7/.local/lib/python3.9/site-packages/astropy/cosmology/flrw.py:1072: IntegrationWarning: The integral is probably divergent, or slowly convergent.
  return quad(self._inv_efunc_scalar, z1, z2, args=self._inv_efunc_scalar_args)[0]
/cosma/home/durham/dc-wils7/DESI/cosmo.py:14: RuntimeWarning: invalid value encountered in log10
  return 5. * np.log10(cosmo.luminosity_distance(zs).value) + 25.
/cosma/home/durham/dc-wils7/.local/lib/python3.9/site-packages/astropy/cosmology/flrw.py:1072: IntegrationWarning: The occurrence of roundoff error is detected, which prevents 
  the requested tolerance from being achieved.  The error may be 
  underestimated.
  return quad(self._inv_efunc_scalar, z1, z2, args=self._inv_efunc_scalar_args)[0]
/cosma/home/durham/dc-wils7/.conda/envs/lumfn/lib/python3.9/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_comoving_distance_z1z2_scalar (vectorized)
  outputs = ufunc(*inputs)
/cosma/home/durham/dc-wils7/.local/lib/python3.9/site-packages/astropy/cosmology/flrw.py:1072: IntegrationWarning: The integral is probably divergent, or slowly convergent.
  return quad(self._inv_efunc_scalar, z1, z2, args=self._inv_efunc_scalar_args)[0]
/cosma/home/durham/dc-wils7/DESI/cosmo.py:14: RuntimeWarning: invalid value encountered in log10
  return 5. * np.log10(cosmo.luminosity_distance(zs).value) + 25.
/cosma/home/durham/dc-wils7/.local/lib/python3.9/site-packages/astropy/cosmology/flrw.py:1072: IntegrationWarning: The occurrence of roundoff error is detected, which prevents 
  the requested tolerance from being achieved.  The error may be 
  underestimated.
  return quad(self._inv_efunc_scalar, z1, z2, args=self._inv_efunc_scalar_args)[0]
/cosma/home/durham/dc-wils7/.conda/envs/lumfn/lib/python3.9/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_comoving_distance_z1z2_scalar (vectorized)
  outputs = ufunc(*inputs)
/cosma/home/durham/dc-wils7/.local/lib/python3.9/site-packages/astropy/cosmology/flrw.py:1072: IntegrationWarning: The integral is probably divergent, or slowly convergent.
  return quad(self._inv_efunc_scalar, z1, z2, args=self._inv_efunc_scalar_args)[0]
/cosma/home/durham/dc-wils7/DESI/cosmo.py:14: RuntimeWarning: invalid value encountered in log10
  return 5. * np.log10(cosmo.luminosity_distance(zs).value) + 25.
/cosma/home/durham/dc-wils7/.local/lib/python3.9/site-packages/astropy/cosmology/flrw.py:1072: IntegrationWarning: The occurrence of roundoff error is detected, which prevents 
  the requested tolerance from being achieved.  The error may be 
  underestimated.
  return quad(self._inv_efunc_scalar, z1, z2, args=self._inv_efunc_scalar_args)[0]
/cosma/home/durham/dc-wils7/.conda/envs/lumfn/lib/python3.9/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_comoving_distance_z1z2_scalar (vectorized)
  outputs = ufunc(*inputs)
/cosma/home/durham/dc-wils7/.local/lib/python3.9/site-packages/astropy/cosmology/flrw.py:1072: IntegrationWarning: The occurrence of roundoff error is detected, which prevents 
  the requested tolerance from being achieved.  The error may be 
  underestimated.
  return quad(self._inv_efunc_scalar, z1, z2, args=self._inv_efunc_scalar_args)[0]
/cosma/home/durham/dc-wils7/.conda/envs/lumfn/lib/python3.9/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_comoving_distance_z1z2_scalar (vectorized)
  outputs = ufunc(*inputs)
/cosma/home/durham/dc-wils7/DESI/cosmo.py:14: RuntimeWarning: invalid value encountered in log10
  return 5. * np.log10(cosmo.luminosity_distance(zs).value) + 25.
/cosma/home/durham/dc-wils7/.local/lib/python3.9/site-packages/astropy/cosmology/flrw.py:1072: IntegrationWarning: The integral is probably divergent, or slowly convergent.
  return quad(self._inv_efunc_scalar, z1, z2, args=self._inv_efunc_scalar_args)[0]
/cosma/home/durham/dc-wils7/DESI/cosmo.py:14: RuntimeWarning: invalid value encountered in log10
  return 5. * np.log10(cosmo.luminosity_distance(zs).value) + 25.
/cosma/home/durham/dc-wils7/.local/lib/python3.9/site-packages/astropy/cosmology/flrw.py:1072: IntegrationWarning: The occurrence of roundoff error is detected, which prevents 
  the requested tolerance from being achieved.  The error may be 
  underestimated.
  return quad(self._inv_efunc_scalar, z1, z2, args=self._inv_efunc_scalar_args)[0]
/cosma/home/durham/dc-wils7/.conda/envs/lumfn/lib/python3.9/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in _integral_comoving_distance_z1z2_scalar (vectorized)
  outputs = ufunc(*inputs)
/cosma/home/durham/dc-wils7/.local/lib/python3.9/site-packages/astropy/cosmology/flrw.py:1072: IntegrationWarning: The integral is probably divergent, or slowly convergent.
  return quad(self._inv_efunc_scalar, z1, z2, args=self._inv_efunc_scalar_args)[0]
