====
Starting job 4785739 at Wed 19 Jan 18:17:33 GMT 2022 for user dc-wils7.
Running on nodes: m5399
====
FIELD SET TO BE G9

Environment:

Code: /cosma/home/durham/dc-wils7/DESI/
Gold output dir.: /cosma5/data/durham/dc-wils7/GAMA4/
Randoms output dir: /cosma5/data/durham/dc-wils7/GAMA4/randoms/
Running randoms pipeline for field G9
Traceback (most recent call last):
  File "/cosma/home/durham/dc-wils7/DESI/gen_rand_ddp_N8.py", line 31, in <module>
    dat = Table.read(fpath)
  File "/cosma/home/durham/dc-wils7/.local/lib/python3.9/site-packages/astropy/table/connect.py", line 62, in __call__
    out = self.registry.read(cls, *args, **kwargs)
  File "/cosma/home/durham/dc-wils7/.local/lib/python3.9/site-packages/astropy/io/registry/core.py", line 184, in read
    fileobj = ctx.__enter__()
  File "/cosma/home/durham/dc-wils7/.conda/envs/lumfn/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/cosma/home/durham/dc-wils7/.local/lib/python3.9/site-packages/astropy/utils/data.py", line 271, in get_readable_fileobj
    fileobj = io.FileIO(name_or_obj, 'r')
FileNotFoundError: [Errno 2] No such file or directory: '/cosma5/data/durham/dc-wils7/GAMA4//gama_gold_ddp_dryrun.fits'
Done.
====
Starting job 4785740 at Wed 19 Jan 18:17:35 GMT 2022 for user dc-wils7.
Running on nodes: m5350
====
FIELD SET TO BE G12

Environment:

Code: /cosma/home/durham/dc-wils7/DESI/
Gold output dir.: /cosma5/data/durham/dc-wils7/GAMA4/
Randoms output dir: /cosma5/data/durham/dc-wils7/GAMA4/randoms/
Running randoms pipeline for field G12
====
Starting job 4785741 at Wed 19 Jan 18:17:38 GMT 2022 for user dc-wils7.
Running on nodes: m5399
====
FIELD SET TO BE G15

Environment:

Code: /cosma/home/durham/dc-wils7/DESI/
Gold output dir.: /cosma5/data/durham/dc-wils7/GAMA4/
Randoms output dir: /cosma5/data/durham/dc-wils7/GAMA4/randoms/
Running randoms pipeline for field G15
Traceback (most recent call last):
  File "/cosma/home/durham/dc-wils7/DESI/gen_rand_ddp_N8.py", line 31, in <module>
    dat = Table.read(fpath)
  File "/cosma/home/durham/dc-wils7/.local/lib/python3.9/site-packages/astropy/table/connect.py", line 62, in __call__
    out = self.registry.read(cls, *args, **kwargs)
  File "/cosma/home/durham/dc-wils7/.local/lib/python3.9/site-packages/astropy/io/registry/core.py", line 184, in read
    fileobj = ctx.__enter__()
  File "/cosma/home/durham/dc-wils7/.conda/envs/lumfn/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/cosma/home/durham/dc-wils7/.local/lib/python3.9/site-packages/astropy/utils/data.py", line 271, in get_readable_fileobj
    fileobj = io.FileIO(name_or_obj, 'r')
FileNotFoundError: [Errno 2] No such file or directory: '/cosma5/data/durham/dc-wils7/GAMA4//gama_gold_ddp_dryrun.fits'
Done.
Done.
